# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushmark < Formula
  desc "Send push notifications to any device via simple CLI"
  homepage "https://github.com/pushmark/pushmark-cli"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.4/pushmark_1.0.4_darwin_amd64.tar.gz"
      sha256 "2d50fce5ca1de5ae056c48f2f1ab408b83010cad6d6421f79235c4730cbdb831"

      def install
        bin.install "pushmark"
      end
    end
    on_arm do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.4/pushmark_1.0.4_darwin_arm64.tar.gz"
      sha256 "895294cf7d33d203783186971368e40423937881553a8f08f67867568339443f"

      def install
        bin.install "pushmark"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.4/pushmark_1.0.4_linux_amd64.tar.gz"
        sha256 "7af7b2f924100a56a89ab70f5a4d69c55ce2c575e0c98d2e10645bb3c0273bd1"

        def install
          bin.install "pushmark"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.4/pushmark_1.0.4_linux_arm64.tar.gz"
        sha256 "dab4a29fe64d0fd0085b9f9931c1e6219c4b5c24ed7a3c0f34b297d65d0420f3"

        def install
          bin.install "pushmark"
        end
      end
    end
  end
end
