# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushmark < Formula
  desc "Send push notifications to any device via simple CLI"
  homepage "https://github.com/pushmark/pushmark-cli"
  version "1.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.6/pushmark_1.0.6_darwin_amd64.tar.gz"
      sha256 "32303edcfe630ac0b91d5a5f4abe4fb73bedc3fad9c99f28f71471221cb91414"

      def install
        bin.install "pushmark"
      end
    end
    on_arm do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.6/pushmark_1.0.6_darwin_arm64.tar.gz"
      sha256 "53b94ae27b63bc401257a16c327ebf2bd7759e9301c91465dcb2f8ec3b898589"

      def install
        bin.install "pushmark"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.6/pushmark_1.0.6_linux_amd64.tar.gz"
        sha256 "85b41060b0956624a12c3a616ee5fdfb8215b864f838e845e6b4fd026e01dacd"

        def install
          bin.install "pushmark"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.6/pushmark_1.0.6_linux_arm64.tar.gz"
        sha256 "a84eec4c48056f3b95b7aa16925d99670a244c933dc4189b9d489cbc36941be9"

        def install
          bin.install "pushmark"
        end
      end
    end
  end
end
